# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

pod 'Stripe'
pod 'Mixpanel'
pod 'Canvas'
pod 'Adjust'
pod 'Branch'
pod 'FCUUID'
pod 'PureLayout'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'FDKeychain'
pod 'SIOSocket'
pod 'AFNetworking'
pod 'Fabric'
pod 'Crashlytics'